### ISSUE TITLE
[Bug: NeoForge]: Crashes with Craftoria 1.8.0

### ISSUE THREAD

**Issue by Shopper7** [Tuinity/Moonrise#73]
### Minecraft Version

1,21,1

### Moonrise Version

0.1.0-beta.8

### Mod Loader

NeoForge

### Logs and Crash Reports

https://mclo.gs/Ghv6ngO

### Additional Context

This is a yet another crash with the same cause.
Happened when exploring the world and loading in already existing/generated chunks. 
Was told by embeddedt to report it here just as it is.
Added mods beyond the modpack: XTones Reworked, XyCraft Core; Overworld; Override, Embeddium, Monocle, Nolijium, Radium, Figura, All The Leaks, Xaero Minimap.

**Comment by jpenilla** [comment]
Please properly fill out the mod incompatibility report for individual conflicting mods. We do not have time to debug modpacks.

The culprit here looks to be pneumaticcraft, if you can confirm it happens with just it and Moonrise (or generally narrow down the mod list to a minimal reproducer) then we can look further after a proper report.
